// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// Blackout Secure Security TXT Generator GitHub Action
// Copyright © 2025-2026 Blackout Secure
// Licensed under Apache License 2.0
// Website: https://blackoutsecure.app
// Repository: https://github.com/blackoutsecure/bos-securitytxt-generator
// Issues: https://github.com/blackoutsecure/bos-securitytxt-generator/issues
// Docs: https://github.com/blackoutsecure/bos-securitytxt-generator#readme
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// Project metadata and branding configuration
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

const HEADER_DIVIDER =
  '# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━';

const PROJECT_CONFIG = {
  // Project identity
  name: 'Blackout Secure Security TXT Generator',
  version: '1.0.0', // keep in sync with package.json via version scripts
  brandingEmoji: '🛡️',

  // Repository information
  repository: {
    url: 'github.com/blackoutsecure/bos-securitytxt-generator',
    issuesUrl: 'github.com/blackoutsecure/bos-securitytxt-generator/issues',
    docsUrl:
      'https://github.com/blackoutsecure/bos-securitytxt-generator#readme',
  },

  // Company information
  companyWebsite: 'https://blackoutsecure.app',

  // Copyright and licensing
  copyrightHolder: 'Blackout Secure',
  copyrightYearStart: 2025,
  copyrightYearEnd: 2026,
  license: 'Apache License 2.0',
  spdxIdentifier: 'Apache-2.0',

  // Attribution
  generatedByComment: 'generated by Blackout Secure Security TXT Generator',

  // Documentation references
  references: {
    securityTxt: 'https://securitytxt.org/',
    rfc9116: 'https://www.rfc-editor.org/rfc/rfc9116',
    disclosureGuidance: 'https://www.first.org/global/sigs/vrdx/vdp-framework',
  },
};

/**
 * Get copyright notice
 * @returns {string} Copyright notice string
 */
function getCopyrightNotice() {
  const { copyrightHolder, copyrightYearStart, copyrightYearEnd } =
    PROJECT_CONFIG;
  const yearRange =
    copyrightYearStart === copyrightYearEnd
      ? copyrightYearStart
      : `${copyrightYearStart}-${copyrightYearEnd}`;
  return `© ${yearRange} ${copyrightHolder}`;
}

/**
 * Get project title with branding
 * @returns {string} Branded project title
 */
function getProjectTitle() {
  return `${PROJECT_CONFIG.brandingEmoji} ${PROJECT_CONFIG.name} v${PROJECT_CONFIG.version}`;
}

/**
 * Get repository URL
 * @returns {string} Repository URL
 */
function getRepositoryUrl() {
  return `📦 ${PROJECT_CONFIG.repository.url}`;
}

/**
 * Get support/issues URL
 * @returns {string} Issues URL
 */
function getSupportUrl() {
  return `💬 Support: ${PROJECT_CONFIG.repository.issuesUrl}`;
}

/**
 * Get documentation URL
 * @returns {string} Docs URL
 */
function getDocsUrl() {
  return `📖 Docs: ${PROJECT_CONFIG.repository.docsUrl}`;
}

/**
 * Get file generation comment
 * @param {string} fileType - Type of file (e.g., 'security.txt')
 * @returns {string} Generation comment
 */
function getGenerationComment(fileType) {
  return `# ${fileType} ${PROJECT_CONFIG.generatedByComment}`;
}

/**
 * Get detailed generation header for security.txt
 * @returns {string} Comment header
 */
function getSecurityTxtHeader() {
  const {
    name,
    version,
    repository,
    copyrightHolder,
    copyrightYearStart,
    copyrightYearEnd,
    license,
    spdxIdentifier,
    companyWebsite,
    references,
  } = PROJECT_CONFIG;

  const yearRange =
    copyrightYearStart === copyrightYearEnd
      ? copyrightYearStart
      : `${copyrightYearStart}-${copyrightYearEnd}`;

  return `${HEADER_DIVIDER}
# ${name} GitHub Action
# Copyright © ${yearRange} ${copyrightHolder}
# Licensed under ${license}
# ${HEADER_DIVIDER}
# Generated by: ${name} v${version}
# SPDX-License-Identifier: ${spdxIdentifier}
# Website: ${companyWebsite}
# Repository: https://${repository.url}
# Issues: https://${repository.issuesUrl}
# Docs: ${repository.docsUrl}
# Security.txt: ${references.securityTxt}
# RFC 9116: ${references.rfc9116}
# VDP Framework: ${references.disclosureGuidance}
#
`;
}

module.exports = {
  PROJECT_CONFIG,
  getCopyrightNotice,
  getProjectTitle,
  getRepositoryUrl,
  getSupportUrl,
  getDocsUrl,
  getGenerationComment,
  getSecurityTxtHeader,
};
